# 开发环境配置
spring:
  # 数据源的配置
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.h2/example
    username: sa
    password: 123456
  # H2的配置
  h2:
    # H2的控制台配置
    console:
      # 可以在浏览器中访问H2的控制台
      enabled: true
  # JPA的配置
  jpa:
    # Hibernate的配置
    hibernate:
      ddl-auto: update
    # 在控制台中打印SQL语句
    show-sql: true